name = "balcony-solar-checker"
compatibility_date = "2024-12-09"
pages_build_output_dir = "frontend/dist"

[build]
command = "npm run build:frontend"
cwd = "./"

[env.production]
name = "balcony-solar-checker-prod"
