name = "balcony-solar-checker"
compatibility_date = "2024-12-09"
pages_build_output_dir = "frontend/dist"

[build]
command = "cd frontend && npm install --legacy-peer-deps && npm run build"
cwd = "./"

[env.production]
name = "balcony-solar-checker-prod"
