name = "balcony-solar-api"
main = "src/index.js"
compatibility_date = "2024-12-09"

[env.production]
name = "balcony-solar-api-prod"
routes = [
  { pattern = "api.solarcurrents.com/*", zone_name = "solarcurrents.com" }
]

[env.staging]
name = "balcony-solar-api-staging"
routes = [
  { pattern = "api-staging.solarcurrents.com/*", zone_name = "solarcurrents.com" }
]
